import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Watch The World From Here",
  description: "Generated by create next app By Your Dear Prajwal Bhrata Shree",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white `}
      >
        <Navbar/>
        <main className="pb-24 md:pb-4 max-w-[100dvw] overflow-hidden">
          {children}
        </main>
      </body>
    </html>
  );
}
